

import 'package:shelfish/utils/strings/strings.dart';

/// Italian strings.
class ItStrings implements Strings {
  @override String get librariesTitle => "Biblioteche";
  @override String get noLibrariesFound => "Nessuna biblioteca";
  @override String get all => "Tutti";
  @override String get book => "libro";
  @override String get books => "libri";
  @override String get importLib => "Importa";
  @override String get newLib => "Nuova";
  @override String get deleteLibraryTitle => "Elimina Biblioteca";
  @override String get deleteLibraryContent => "Vuoi davvero eliminare";
  @override String get yes => "Sì";
  @override String get no => "No";
  @override String get ok => "OK";
  @override String get authorInfo => "Scheda Autore";
  @override String get genreInfo => "Scheda Genere";
  @override String get publisherInfo => "Scheda Editore";
  @override String get bookInfo => "Scheda Libro";
  @override String get firstName => "Nome";
  @override String get lastName => "Cognome";
  @override String get bookEdit => "Modifica";
  @override String get bookMoveTo => "Sposta in";
  @override String get bookDelete => "Elimina";
  @override String get deleteBookTitle => "Elimina";
  @override String get deleteBookContent => "Vuoi davvero eliminare questo libro?";
  @override String get bookInfoTitle => "Titolo";
  @override String get bookInfoLibrary => "Biblioteca";
  @override String get bookInfoAuthors => "Autori";
  @override String get bookInfoPublishDate => "Anno di pubblicazione";
  @override String get bookInfoGenres => "Generi";
  @override String get bookInfoPublisher => "Editore";
  @override String get bookInfoLocation => "Posizione";
  @override String get insertTitle => "Inserisci";
  @override String get editTitle => "Modifica";
  @override String get authorTitle => "Autore";
  @override String get authorInfoFirstName => "Nome";
  @override String get authorInfoLastName => "Cognome";
  @override String get editDone => "Fine";
  @override String get bookTitle => "Libro";
  @override String get addOne => "Aggiungi";
  @override String get add => "Nuovo";
  @override String get authorAlreadyAdded => "Autore già aggiunto";
  @override String get genreAlreadyAdded=> "Genere già aggiunto";
  @override String get selectPublishYear => "Seleziona anno di pubblicazione";
  @override String get select => "Seleziona";
  @override String get publishers => "Editori";
  @override String get locations => "Posizioni";
  @override String get bookErrorNoTitleProvided => "Inserire un titolo";
  @override String get genreTitle=> "Genere";
  @override String get genreInfoName=> "Nome";
  @override String get genreInfoColor => "Colore";
  @override String get genrePickColor => "Scegli un colore";
  @override String get libraryTitle => "Biblioteca";
  @override String get libraryInfoName => "Nome";
  @override String get locationTitle => "Posizione";
  @override String get locationInfoName => "Nome";
  @override String get publisherTitle => "Editore";
  @override String get publisherInfoName => "Nome";
  @override String get booksSectionTitle => "Libri";
  @override String get genresSectionTitle => "Generi";
  @override String get authorsSectionTitle => "Autori";
  @override String get publishersSectionTitle => "Editori";
  @override String get locationsSectionTitle => "Posizioni";
  @override String get filterLibrary => "Filtra";
  @override String get shareLibrary => "Condividi";
  @override String get exportLibrary => "Esporta";
  @override String get updateLibrary => "Aggiorna";
  @override String get filterTitle => "Filtro";
  @override String get filterApply => "Applica";
  @override String get filterCancel => "Annulla";
  @override String get filteredBooksTitle => "Libri filtrati";
}